services:
  db:
    image: postgres:16
    container_name: cblab-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cblab_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data_lake_network

  etl:
    build: .
    container_name: cblab-etl
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cblab_db
      DB_HOST: db
    command: sh -c "./wait-for-it.sh db && python etl.py"
    networks:
      - data_lake_network

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio_data:/data
    networks:
      - data_lake_network

networks:
  data_lake_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: